language: java
env:
  matrix:
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  global:
  - secure: r1R8NP699Qw2/t3sEGDkCJrIIeYU9byC6bIIKjIcG4zzf9Qy2fkHD5MHmJAXEB7Z/OCUUZZNEWzZhjgBAIrN0u3nN7lsIR2YYFfnmsaGJSTBQM2ItU1wKrIzQdrqa3ZVPitjQ8BJ6JMalr0qNS2wHcTnAskXDpjl8d1lNFeA8feNKKSLrUcFKMlGTtioe7aeaD0birawF35j35rzQA9XItydjpMoChdL4/uAe7JGZM6TJt3VqJ3kMgWWmJ6JkMOGFX+cWAw+G5MV4DN39Jy6mGmcJv0qPE2yG3CAewl74/pHmyYVOwjS+Bw3NbgNrLQlqJ1n/wUC9S6cZEsiqUgUOpLTLgarjrkCoNGXJfCKO09cljEQJqu8TiP8pskiC74ytBp6Mkuk5b+kK3pko9ggmWDjn2I1qjF/bPZBCog0+rnyD3Y09jf9y0LtO2/Um0kwHNPY/sSszPMQ8S5P4cg4IEWGu1/SZH64ohCCoL1eTjhHm6T31mxPj6YxEafHUVLoqfiOGuzChXc+6UIyCVACn++KWs/wrCFPs4EiVyl4ymKZupHWgzUI4pEsmd63J+tw1sPJjSZ9y9K0UQbB/oGTVFzuob2FWXmXXARWownno1Z00KTn3PrDTsUKkRQq+9AC5LCtKvYz9Rslxmn7V1zoR/1CRQAv+s4ZlUG/W7lwel0=
jdk:
- oraclejdk7
script:
- echo "FOO"
notifications:
  email: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
after_success:
- .travis/after_success.sh
before_install:
- .travis/before_install.sh
