language: java
env:
  matrix:
  - IDEA_VERSION=IC-15.0.4
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
jdk:
- oraclejdk7
script:
- echo "FOO"
notifications:
  email: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
after_success:
- .travis/after_success.sh
before_install:
- openssl aes-256-cbc -K $encrypted_1e50d859c9d1_key -iv $encrypted_1e50d859c9d1_iv
  -in travis.enc -out ~\/.travis -d
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/travis/travis\n" >> ~/.travix
