language: java
env:
  matrix:
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
jdk:
- oraclejdk7
script:
- echo "FOO"
notifications:
  email: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
after_success:
- .travis/after_success.sh
before_install:
- .travis/before_install.sh
